"""empty message

Revision ID: b39779f41eda
Revises: 9f97debcf936
Create Date: 2025-09-24 13:00:46.218569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39779f41eda'
down_revision: Union[str, Sequence[str], None] = '9f97debcf936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'calls', ['id'])
    op.create_unique_constraint(None, 'records', ['id'])
    op.create_unique_constraint(None, 'silent_ranges', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'silent_ranges', type_='unique')
    op.drop_constraint(None, 'records', type_='unique')
    op.drop_constraint(None, 'calls', type_='unique')
    # ### end Alembic commands ###
