"""
empty message.

Revision ID: d6a214f1cc75
Revises:
Create Date: 2025-09-25 15:32:11.037149

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6a214f1cc75"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calls",
        sa.Column("caller", sa.String(), nullable=False),
        sa.Column("receiver", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CREATED", "PROCESSING", "READY", name="callstatus"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_calls_caller"), "calls", ["caller"], unique=False)
    op.create_index(op.f("ix_calls_receiver"), "calls", ["receiver"], unique=False)
    op.create_table(
        "records",
        sa.Column("call_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("object_path", sa.String(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=False),
        sa.Column("transcription", sa.String(), nullable=False),
        sa.Column("presigned_url", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["call_id"], ["calls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("call_id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "silent_ranges",
        sa.Column("record_id", sa.Uuid(), nullable=False),
        sa.Column("start", sa.Float(), nullable=False),
        sa.Column("end", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["record_id"], ["records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("silent_ranges")
    op.drop_table("records")
    op.drop_index(op.f("ix_calls_receiver"), table_name="calls")
    op.drop_index(op.f("ix_calls_caller"), table_name="calls")
    op.drop_table("calls")
    # ### end Alembic commands ###
