apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    orgId: 1
    url: http://${LOKI_HOST}:${LOKI_PORT}
    isDefault: true
    version: 1
    editable: false
